backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "productos"
    label: "Productos"
    files:
      - label: "Lista de Precios"
        name: "precios"
        file: "productos.json"
        fields:
          - label: "Productos"
            name: "productos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Precio", name: "precio", widget: "string" }
              - { label: "ID", name: "tamano", widget: "string", required: true }
              - { label: "Link", name: "link", widget: "string" }

  - name: "eventos"
    label: "Página de Eventos"
    files:
      - label: "Evento Actual"
        name: "evento"
        file: "eventos.json"
        fields:
          - { label: "Título del Header", name: "header_titulo", widget: "string" }
          - { label: "Texto del Cuerpo", name: "texto_body", widget: "text" }
          - { label: "Imagen Superior Izquierda", name: "imagen_superior_izq", widget: "image" }
          - { label: "Imagen Medio Derecha", name: "imagen_medio_derecha", widget: "image" }
          - { label: "Imagen de Fondo (transparente)", name: "background_imagen", widget: "image" }
          - { label: "Imagen de Portada", name: "imagen_portada", widget: "image" }
